---
roles:
  # Install a role from Ansible Galaxy.
  #- name: sample
  #  version: 1.9.6

collections:
  # Install a collection from Ansible Galaxy.
  - name: amazon.aws
    #version: 2.0.0
    source: https://galaxy.ansible.com
  - name: community.general
    #version: 4.0.1
    source: https://galaxy.ansible.com
  - name: ansible.posix
    #version: 1.3.0
    source: https://galaxy.ansible.com
