
variable "client_id" {
  type    = string
  default = "63b9e4cb-3313-40a1-ba00-30614fec5143"
}

variable "client_secret" {
  type    = string
  default = "00X8Q~rt5RfIOeinGz9rwN2cUO-MnUmOpRIJhaGu"
}

variable "resource_group" {
  type    = string
  default = "1-8752266d-playground-sandbox"
}

variable "subscription_id" {
  type    = string
  default = "964df7ca-3ba4-48b6-a695-1ed9db5723f8"
}

locals { timestamp = regex_replace(timestamp(), "[- TZ:]", "") }

source "azure-arm" "autogenerated_1" {
  azure_tags = {
    role = "web"
    team = "frontend"
  }
  build_resource_group_name         = "${var.resource_group}"
  client_id                         = "${var.client_id}"
  client_secret                     = "${var.client_secret}"
  image_offer                       = "UbuntuServer"
  image_publisher                   = "Canonical"
  image_sku                         = "18.04-LTS"
  managed_image_name                = "packer-booksite-${local.timestamp}"
  managed_image_resource_group_name = "${var.resource_group}"
  os_type                           = "Linux"
  subscription_id                   = "${var.subscription_id}"
  vm_size                           = "Standard_A1_V2"
}

build {
  sources = ["source.azure-arm.autogenerated_1"]

  provisioner "shell" {
    execute_command = "chmod +x {{ .Path }}; {{ .Vars }} sudo -E sh '{{ .Path }}'"
    inline          = ["/usr/sbin/waagent -force -deprovision+user && export HISTSIZE=0 && sync"]
    inline_shebang  = "/bin/sh -x"
  }

}
