---
# Using my DO inventory - held in private repo cloned locally
# ansible-playbook -i ../do_inventory/inventory webservers.yaml -e 'host_name=all' 
- name: Install the apache web service
  #could use this if inventory is grouped see hosts-ec2
  #  hosts: webservers 
  #hosts: all
  # test Ansible Tower Survey
  hosts: '{{ host_name }}'

  tasks:

    - name: CENTOS Webservers setup  
      block: 
        - name: install packages
          become: true
          become_user: root
          action: >
           {{ ansible_pkg_mgr }} name=httpd state=present update_cache=yes

        - name: start httpd
          ignore_errors: yes
          service:
            name: httpd
            state: started        
  
      when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"
      

    - name: UBUNTU Webservers setup  
      block: 
        - name: install packages
          become: true
          become_user: root
          action: >
           {{ ansible_pkg_mgr }} name=apache2 state=present update_cache=yes

        - name: start httpd
          ignore_errors: yes
          service:
            name: apache2
            state: started        

      when: ansible_distribution == "Ubuntu"
