---
# tasks file for aws-get-vpc-details
- name: Get VPC Details
  amazon.aws.ec2_vpc_net_info:
    profile: "{{ aws_boto_profile }}"
    region: "{{ aws_region }}"
  register: aws_vpc_details
  #  filters:
  #    "tag:Name": Example

- name: Collect VPC ID
  set_fact:
    aws_vpc_id: "{{ aws_vpc_details.vpcs[0].vpc_id }}"

- name: Fetch VPC Subnets
  ec2_vpc_subnet_info:
    profile: "{{ aws_boto_profile }}"
    region: "{{ aws_region }}"
  register: aws_vpc_subnet_details

- name: Collect VPC Subnets
  #debug:
  #  msg: "{{ item.subnet_id }}"
  set_fact:  
    vpc_subnet_list: "{{ vpc_subnet_list }} + [ '{{ item.subnet_id }}' ]"
  loop: "{{ aws_vpc_subnet_details.subnets }}"