version: 1
build_arg_defaults:
  EE_BASE_IMAGE: 'registry.redhat.io/ansible-automation-platform-21/ee-29-rhel8'
dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  # system: bindep.txt
additional_build_steps:
  prepend: |
    RUN pip3 install --upgrade pip setuptools urllib3
